CREATE TABLE `payment_logs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `payment_for` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ref_id` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_type` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `easepayid` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deduction_percentage` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `net_amount_debit` decimal(10,2) DEFAULT NULL,
  `cardCategory` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unmappedstatus` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `addedon` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cash_back_percentage` decimal(10,2) DEFAULT NULL,
  `bank_ref_num` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `error_Message` longtext COLLATE utf8mb4_unicode_ci,
  `phone` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `cardnum` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `upi_va` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `payment_source` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `card_type` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mode` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `error` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bankcode` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_on_card` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bank_name` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `issuing_bank` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PG_TYPE` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `amount` decimal(10,2) DEFAULT NULL,
  `furl` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `productinfo` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `auth_code` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hash` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `firstname` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `surl` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `key` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `merchant_logo` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `txnid` longtext COLLATE utf8mb4_unicode_ci,
  `udf1` longtext COLLATE utf8mb4_unicode_ci,
  `udf2` longtext COLLATE utf8mb4_unicode_ci,
  `udf3` longtext COLLATE utf8mb4_unicode_ci,
  `udf4` longtext COLLATE utf8mb4_unicode_ci,
  `udf5` longtext COLLATE utf8mb4_unicode_ci,
  `udf6` longtext COLLATE utf8mb4_unicode_ci,
  `udf7` longtext COLLATE utf8mb4_unicode_ci,
  `udf8` longtext COLLATE utf8mb4_unicode_ci,
  `udf9` longtext COLLATE utf8mb4_unicode_ci,
  `udf10` longtext COLLATE utf8mb4_unicode_ci,
  `cancellation_reason` longtext COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
