CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_type` enum('SUPERADMIN','FREELANCER','CA','ADMIN','CLIENT') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `company_type_id` int(11) DEFAULT NULL,
  `profile_picture` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `first_name` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `middle_name` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `last_name` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email_verified_at` datetime DEFAULT NULL,
  `mobile_no` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobile_no_verified_at` datetime DEFAULT NULL,
  `whats_app_no` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `corr_address` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `corr_pincode` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `corr_state_id` int(11) DEFAULT NULL,
  `corr_city_id` int(11) DEFAULT NULL,
  `per_address` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `per_pincode` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `per_state_id` int(11) DEFAULT NULL,
  `per_city_id` int(11) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `gender` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hash_key` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_active` int(1) DEFAULT '1',
  `remark` varchar(225) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `cretead_by` int(11) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `updated_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
