CREATE TABLE `user_added_services` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `service_no` varchar(225) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `master_service_id` int(11) DEFAULT NULL,
  `assigned_to_user_id` int(11) DEFAULT NULL,
  `assigned_at` datetime DEFAULT NULL,
  `current_stage` enum('DOCUMENT','PAYMENT','WORK_IN_PROGRESS') DEFAULT NULL,
  `current_status` enum('IN_PROGRESS','HOLD','COMPLETE','HOLD_FOR_BALANCE_PAYMENT') DEFAULT NULL,
  `status_changed_at` datetime DEFAULT NULL,
  `is_work_verified` int(1) DEFAULT '0',
  `work_verified_at` datetime DEFAULT NULL,
  `total_documents` int(11) DEFAULT NULL,
  `uploaded_documents` int(11) DEFAULT '0',
  `remaining_documents` int(11) DEFAULT NULL,
  `all_document_verified` int(1) DEFAULT '0',
  `user_added_service_payment_id` int(11) DEFAULT NULL,
  `payment_type` enum('ADVANCE_PAYMENT','FULL_PAYMENT','BALANCE_PAYMENT','PAYMENT_COMPLETE') DEFAULT NULL,
  `total_amount` decimal(10,2) DEFAULT '0.00',
  `total_advance_amount` decimal(10,2) DEFAULT '0.00',
  `total_paid_amount` decimal(10,2) DEFAULT '0.00',
  `total_balance_amount` decimal(10,2) DEFAULT '0.00',
  `last_transaction_status` varchar(225) DEFAULT NULL,
  `last_transaction_at` datetime DEFAULT NULL,
  `remark` varchar(225) DEFAULT NULL,
  `is_active` int(1) DEFAULT '1',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
